version: "3"
  

services:
    app:
    container_name: myprofile
    image: djangoapp
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
